{{- range $index, $cronjob  := .Values.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: echo-{{ $index }}
spec:
  schedule: {{ $cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: container
              image: "busybox"
              command: [ "echo" ]
              args: [ {{ $cronjob.output | quote }} ]
          restartPolicy: "Never"
{{- end}}
